# Generated by Django 4.2.9 on 2024-02-05 12:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Staff',
            fields=[
                ('email', models.EmailField(max_length=254)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('address', models.CharField(max_length=500)),
                ('is_doctor', models.BooleanField(default=False)),
                ('mobile', models.CharField(max_length=20)),
                ('nationality', models.CharField(max_length=40, null=True)),
                ('custom_id', models.CharField(default='', editable=False, max_length=8, unique=True)),
            ],
        ),
    ]
