# Generated by Django 4.2.9 on 2024-02-05 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='healthit_staff',
            field=models.BooleanField(default=True),
        ),
    ]
