# Generated by Django 4.2.9 on 2024-02-10 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0005_department'),
        ('staff', '0003_remove_staff_is_doctor'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='department',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff', to='members.department'),
        ),
    ]
