# Generated by Django 4.2.9 on 2024-02-28 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0014_plan_alerts_plan_care_staff_available_and_more'),
        ('staff', '0005_staff_member'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='member',
        ),
        migrations.AddField(
            model_name='staff',
            name='members',
            field=models.ManyToManyField(related_name='staff', to='members.member'),
        ),
    ]
