# Generated by Django 4.2.9 on 2024-03-01 09:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0006_remove_staff_member_staff_members'),
    ]

    operations = [
        migrations.AddField(
            model_name='staff',
            name='doctors',
            field=models.BooleanField(default=False),
        ),
    ]
