# Generated by Django 4.2.9 on 2024-03-01 12:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0007_staff_doctor'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='staff',
            name='doctors',
        ),
    ]
