# Generated by Django 4.2.9 on 2024-03-02 04:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('staff', '0009_scheduleblock'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduleblock',
            name='desc',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
