# Generated by Django 4.2.9 on 2024-02-09 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0004_rename_member_question_member'),
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Dept_id', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=50)),
            ],
        ),
    ]
