# Generated by Django 4.2.9 on 2024-02-11 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0006_member_gender'),
    ]

    operations = [
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('plan_id', models.CharField(default='', editable=False, max_length=10, unique=True)),
                ('name', models.CharField(max_length=25)),
                ('price', models.IntegerField(max_length=10)),
                ('plan_type', models.CharField(max_length=25)),
            ],
        ),
    ]
