# Generated by Django 4.2.9 on 2024-02-11 09:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0007_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='validity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='plan',
            name='price',
            field=models.IntegerField(),
        ),
    ]
