# Generated by Django 4.2.9 on 2024-02-13 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0008_plan_validity_alter_plan_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.IntegerField(),
        ),
    ]
