# Generated by Django 4.2.9 on 2024-02-13 13:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0009_alter_plan_validity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='validity',
            field=models.IntegerField(null=True),
        ),
    ]
