# Generated by Django 4.2.9 on 2024-02-13 14:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0011_member_plan'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='member', to='members.plan'),
        ),
    ]
