# Generated by Django 4.2.9 on 2024-02-18 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0013_alter_member_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan',
            name='alerts',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='care_staff_available',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='dedicated_services',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='free_laboratory',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='free_pharmacy',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='plan',
            name='video_consultation',
            field=models.BooleanField(default=False),
        ),
    ]
