# Generated by Django 4.2.9 on 2024-03-09 09:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('members', '0015_appointmentrequset'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointmentrequset',
            name='member',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='appointment_requests', to='members.member'),
        ),
    ]
